ESX = nil
TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)

local Bones = {
    [0] = { name = "SKEL_ROOT", label = "Onbekend (ergens in lichaam)" },
    [11816] = { name = "SKEL_Pelvis", label = "Bekken" },
    [58271] = { name = "SKEL_L_Thigh", label = "L. Bovenbeen" },
    [63931] = { name = "SKEL_L_Calf", label = "L. Onderbeen" },
    [14201] = { name = "SKEL_L_Foot", label = "L. Voet" },
    [2108] = { name = "SKEL_L_Toe0", label = "L. Teen" },
    [33989] = { name = "EO_L_Foot" },
    [26813] = { name = "EO_L_Toe" },
    [65245] = { name = "IK_L_Foot" },
    [57717] = { name = "PH_L_Foot" },
    [46078] = { name = "MH_L_Knee" },
    [51826] = { name = "SKEL_R_Thigh", label = "R. Bovenbeen" },
    [36864] = { name = "SKEL_R_Calf", label = "R. Onderbeen" },
    [52301] = { name = "SKEL_R_Foot", label = "R. Voet" },
    [20781] = { name = "SKEL_R_Toe0", label = "R. Teen" },
    [4246] = { name = "EO_R_Foot" },
    [29027] = { name = "EO_R_Toe" },
    [35502] = { name = "IK_R_Foot" },
    [24806] = { name = "PH_R_Foot" },
    [16335] = { name = "MH_R_Knee" },
    [23639] = { name = "RB_L_ThighRoll" },
    [6442] = { name = "RB_R_ThighRoll" },
    [57597] = { name = "SKEL_Spine_Root" },
    [23553] = { name = "SKEL_Spine0" },
    [24816] = { name = "SKEL_Spine1" },
    [24817] = { name = "SKEL_Spine2" },
    [24818] = { name = "SKEL_Spine3" },
    [64729] = { name = "SKEL_L_Clavicle", label = "L. Sleutelbeen" },
    [45509] = { name = "SKEL_L_UpperArm", label = "L. Bovenarm" },
    [61163] = { name = "SKEL_L_Forearm", label = "L. Onderarm" },
    [18905] = { name = "SKEL_L_Hand", label = "L. Hand" },
    [26610] = { name = "SKEL_L_Finger00" },
    [4089] = { name = "SKEL_L_Finger01" },
    [4090] = { name = "SKEL_L_Finger02" },
    [26611] = { name = "SKEL_L_Finger10" },
    [4169] = { name = "SKEL_L_Finger11" }, -- SKEL_L_Finger11 = 0x1049,
    [4170] = { name = "SKEL_L_Finger12" }, -- SKEL_L_Finger12 = 0x104A,
    [26612] =  { name = "SKEL_L_Finger20" },
    [4185] = { name = "SKEL_L_FINGER21" }, -- SKEL_L_Finger21 = 0x1059,
    [4186] = { name = "SKEL_L_Finger22" }, -- SKEL_L_Finger22 = 0x105A,
    [26613] = { name = "SKEL_L_Finger30" }, -- SKEL_L_Finger30 = 0x67F5,
    [4137] = { name = "SKEL_L_Finger31" }, -- SKEL_L_Finger31 = 0x1029,
    [4138] = { name = "SKEL_L_Finger32" }, -- SKEL_L_Finger32 = 0x102A,
    [26614] = { name = "SKEL_L_Finger40" }, -- SKEL_L_Finger40 = 0x67F6,
    [4153] = { name = "SKEL_L_Finger41" }, -- SKEL_L_Finger41 = 0x1039,
    [4154] = { name = "SKEL_L_Finger42" }, -- SKEL_L_Finger42 = 0x103A,
    [60309] = { name = "PH_L_Hand" },
    [36029] = { name = "IK_L_Hand" },
    [61007] = { name = "RB_L_ForeArmRoll" },
    [5232] = { name = "RB_L_ArmRoll" },
    [22711] = { name = "MH_L_Elbow" },
    [10706] = { name = "SKEL_R_Clavicle", label = "R. Sleutelbeen" },
    [40269] = { name = "SKEL_R_UpperArm", label = "R. Bovenarm" },
    [28252] = { name = "SKEL_R_Forearm", label = "R. Onderarm" },
    [57005] = { name = "SKEL_R_Hand", label = "R. Hand" },
    [58866] = { name = "SKEL_R_Finger00" },
    [64016] = { name = "SKEL_R_Finger01" },
    [64017] = { name = "SKEL_R_Finger02" },
    [58867] = { name = "SKEL_R_Finger10" },
    [64096] = { name = "SKEL_R_Finger11" }, -- SKEL_R_Finger11 = 0xFA60,
    [64097] = { name = "SKEL_R_Finger12" }, -- SKEL_R_Finger12 = 0xFA61,
    [58868] = { name = "SKEL_R_Finger20" }, -- SKEL_R_Finger20 = 0xE5F4,
    [64112] = { name = "SKEL_R_Finger21" }, -- SKEL_R_Finger21 = 0xFA70,
    [64113] = { name = "SKEL_R_Finger22" }, -- SKEL_R_Finger22 = 0xFA71,
    [58869] = { name = "SKEL_R_Finger30" }, -- SKEL_R_Finger30 = 0xE5F5,
    [64064] = { name = "SKEL_R_Finger31" }, -- SKEL_R_Finger31 = 0xFA40,
    [64065] = { name = "SKEL_R_Finger32" }, -- SKEL_R_Finger32 = 0xFA41,
    [58870] = { name = "SKEL_R_Finger40" }, -- SKEL_R_Finger40 = 0xE5F6,
    [64080] = { name = "SKEL_R_Finger41" }, -- SKEL_R_Finger41 = 0xFA50,
    [64081] = { name = "SKEL_R_Finger42" },-- SKEL_R_Finger42 = 0xFA51,
    [28422] =  { name = "PH_R_Hand" },
    [6286] =  { name = "IK_R_Hand" },
    [43810] =  { name = "RB_R_ForeArmRoll" },
    [37119] =  { name = "RB_R_ArmRoll" },
    [2992] =  { name = "MH_R_Elbow" },
    [39317] =  { name = "SKEL_Neck_1" },
    [31086] =  { name = "SKEL_Head" },
    [12884] =  { name = "IK_Head" },
    [65068] =  { name = "FACIAL_facialRoot" },
    [25260] =  { name = "FB_L_Eye_000" },
    [21550] =  { name = "FB_L_CheekBone_000" },
    [27474] =  { name = "FB_R_Eye_000" },
    [19336] =  { name = "FB_R_CheekBone_000" },
    [35731] =  { name = "RB_Neck_1" },
    [64654] =  { name = "SPR_L_Breast" },
    [34911] =  { name = "SPR_R_Breast" },
    [56604] =  { name = "IK_Root" },
    [24532] =  { name = "SKEL_Neck_2" },
    [53251] =  { name = "SKEL_Pelvis1" },
    [17916] =  { name = "SKEL_PelvisRoot" },
    [38180] =  { name = "SKEL_SADDLE" },
    [3515] =  { name = "SM_M_BackSkirtRoll" },
    [50813] =  { name = "SM_CockNBalls_ROOT" },
    [40244] =  { name = "SM_CockNBalls" },
    [35939] =  { name = "MH_L_Finger00" },
    [24504] =  { name = "MH_L_FingerBulge00" },
    [35923] =  { name = "MH_L_Finger10" },
    [41540] =  { name = "MH_L_FingerTop00" },
    [10040] =  { name = "MH_Watch" },
    [2849] =  { name = "FACIAL_jaw" },
    [35477] =  { name = "FACIAL_underChin" },
    [9038] =  { name = "FACIAL_L_underChin" },
    [46456] =  { name = "FACIAL_chin" },
    [37400] =  { name = "FACIAL_forehead" },
    [16929] =  { name = "FACIAL_skull" },
    [44912] =  { name = "FACIAL_L_temple" },
    [7382] =  { name = "FACIAL_R_noseUpper" },
    [44825] =  { name = "FACIAL_R_temple" },
    [34577] =  { name = "MH_L_ShoulderBladeRoot" },
    [20143] =  { name = "MH_L_ShoulderBlade" },
    [14858] =  { name = "MH_R_ShoulderBladeRoot" },
    [21679] =  { name = "MH_R_ShoulderBlade" },
    [7531] =  { name = "SKEL_L_Toe1" },
    [45631] =  { name = "SKEL_R_Toe1" },
}

local Weapons = {
    [-842959696] = "WEAPON_FALL",
    [911657153] = "Stun Gun (WEAPON_STUNGUN)",
    [4194021054] = "WEAPON_ANIMAL",
    [148160082] = "WEAPON_COUGAR",
    [-1716189206] = "Knife (WEAPON_KNIFE)",
    [-581044007] = "Machete (WEAPON_MACHETE)",
    [1737195953] = "Night Stick (WEAPON_NIGHTSTICK)",
    [1317494643] = "Hammer (WEAPON_HAMMER)",
    [-1786099057] = "Bat (WEAPON_BAT)",
    [1141786504] = "WEAPON_GOLFCLUB",
    [2227010557] = "WEAPON_CROWBAR",
    [453432689] = "Pistol (WEAPON_PISTOL)",
    [1593441988] = "Combat Pistol (WEAPON_COMBATPISTOL)",
    [584646201] = "AP Pistol (WEAPON_APPISTOL)",
    [-1716589765] = "Pistol .50 (WEAPON_PISTOL50)",
    [324215364] = "Micro SMG (WEAPON_MICROSMG)",
    [736523883] = "SMG (MP5) (WEAPON_SMG)",
    [2937143193] = "Advanced Rifle (WEAPON_ADVANCEDRIFLE)",
    [2634544996] = "MG (WEAPON_MG)",
    [2144741730] = "Combat MG (WEAPON_COMBATMG)",
    [487013001] = "Pump Shotgun (WEAPON_PUMPSHOTGUN)",
    [-1569615261] = "Unarmed (WEAPON_UNARMED)",
    [205991906] = "Heavy Sniper (WEAPON_HEAVYSNIPER)",
    [100416529] = "Sniper Rifle (WEAPON_SNIPERRIFLE)",
    [-270015777] = "Assault SMG (WEAPON_ASSAULTSMG)",
    [-1660422300] = "MG (WEAPON_MG)",
    [-2084633992] = "Carbine Rifle (M4A1) (WEAPON_CARBINERIFLE)",
    [-1074790547] = "Assault Rifle (AK47) (WEAPON_ASSAULTRIFLE)",
    [2017895192] = "Sawed-Off Shotgun (WEAPON_SAWNOFFSHOTGUN)",
    [3800352039] = "Assault Shotgun (WEAPON_ASSAULTSHOTGUN)",
    [2640438543] = "Bullpup Shotgun (WEAPON_BULLPUPSHOTGUN)",
    [1595421922] = "Molotok Gun (WEAPON_MOLOTOK)",
    [-1553120962] = "Run Over (WEAPON_RUN_OVER_BY_CAR)",
    [-868994466] = "Fire Truck (WEAPON)",
    [`WEAPON_UNARMED`] = 'Unarmed (WEAPON_UNARMED)',
	[`WEAPON_KNIFE`] = 'Knife (WEAPON_KNIFE)',
	[`WEAPON_NIGHTSTICK`] = 'Nightstick (WEAPON_NIGHTSTICK)',
	[`WEAPON_HAMMER`] = 'Hammer (WEAPON_HAMMER)',
	[`WEAPON_BAT`] = 'Baseball Bat (WEAPON_BAT)',
	[`WEAPON_GOLFCLUB`] = 'Golf Club (WEAPON_GOLFCLUB)',
	[`WEAPON_CROWBAR`] = 'Crowbar (WEAPON_CROWBAR)',
	[`WEAPON_PISTOL`] = 'Pistol (WEAPON_PISTOL)',
	[`WEAPON_PISTOL_MK2`] = 'Beretta (WEAPON_PISTOL_MK2)',
	[`WEAPON_COMBATPISTOL`] = 'Combat Pistol (WEAPON_COMBATPISTOL)',
	[`WEAPON_APPISTOL`] = 'AP Pistol (WEAPON_APPISTOL)',
	[`WEAPON_PISTOL50`] = 'Pistol .50 (WEAPON_PISTOL50)',
	[`WEAPON_MICROSMG`] = 'Micro SMG (WEAPON_MICROSMG)',
	[`WEAPON_SMG`] = 'SMG (WEAPON_SMG)',
	[`WEAPON_ASSAULTSMG`] = 'Assault SMG (WEAPON_ASSAULTSMG)',
	[`WEAPON_ASSAULTRIFLE`] = 'Assault Rifle (AK-47) (WEAPON_ASSAULTRIFLE)',
	[`WEAPON_CARBINERIFLE`] = 'Carbine Rifle (M4A1) (WEAPON_CARBINERIFLE)',
	[`WEAPON_CARBINERIFLE_MK2`] = 'Carbine Rifle MK2 (HK416) (WEAPON_CARBINERIFLE_MK2)',
	[`WEAPON_ADVANCEDRIFLE`] = 'Advanced Rifle (WEAPON_ADVANCEDRIFLE)',
	[`WEAPON_MG`] = 'MG (WEAPON_MG)',
	[`WEAPON_COMBATMG`] = 'Combat MG (WEAPON_COMBATMG)',
	[`WEAPON_PUMPSHOTGUN`] = 'Pump Shotgun (WEAPON_PUMPSHOTGUN)',
	[`WEAPON_SAWNOFFSHOTGUN`] = 'Sawed-Off Shotgun (WEAPON_SAWNOFFSHOTGUN)',
	[`WEAPON_ASSAULTSHOTGUN`] = 'Assault Shotgun (WEAPON_ASSAULTSHOTGUN)',
	[`WEAPON_BULLPUPSHOTGUN`] = 'Bullpup Shotgun (WEAPON_BULLPUPSHOTGUN)',
	[`WEAPON_STUNGUN`] = 'Stun Gun (WEAPON_STUNGUN)',
	[`WEAPON_SNIPERRIFLE`] = 'Sniper Rifle (WEAPON_SNIPERRIFLE)',
	[`WEAPON_HEAVYSNIPER`] = 'Heavy Sniper (WEAPON_HEAVYSNIPER)',
	[`WEAPON_REMOTESNIPER`] = 'Remote Sniper (WEAPON_REMOTESNIPER)',
	[`WEAPON_GRENADELAUNCHER`] = 'Grenade Launcher (WEAPON_GRENADELAUNCHER)',
	[`WEAPON_GRENADELAUNCHER_SMOKE`] = 'Smoke Grenade Launcher (WEAPON_GRENADELAUNCHER_SMOKE)',
	[`WEAPON_RPG`] = 'RPG (WEAPON_RPG)',
	[`WEAPON_PASSENGER_ROCKET`] = 'Passenger Rocket (WEAPON_PASSENGER_ROCKET)',
	[`WEAPON_AIRSTRIKE_ROCKET`] = 'Airstrike Rocket (WEAPON_AIRSTRIKE_ROCKET)',
	[`WEAPON_STINGER`] = 'Stinger [Vehicle] (WEAPON_STINGER)',
	[`WEAPON_MINIGUN`] = 'Minigun (WEAPON_MINIGUN)',
	[`WEAPON_GRENADE`] = 'Grenade (WEAPON_GRENADE)',
	[`WEAPON_STICKYBOMB`] = 'Sticky Bomb (WEAPON_STICKYBOMB)',
	[`WEAPON_SMOKEGRENADE`] = 'Tear Gas (WEAPON_SMOKEGRENADE)',
	[`WEAPON_BZGAS`] = 'BZ Gas (WEAPON_BZGAS)',
	[`WEAPON_MOLOTOV`] = 'Molotov (WEAPON_MOLOTOV)',
	[`WEAPON_FIREEXTINGUISHER`] = 'Fire Extinguisher (WEAPON_FIREEXTINGUISHER)',
	[`WEAPON_PETROLCAN`] = 'Jerry Can (WEAPON_PETROLCAN)',
	[`OBJECT`] = 'Object',
	[`WEAPON_BALL`] = 'Ball (WEAPON_BALL)',
	[`WEAPON_FLARE`] = 'Flare (WEAPON_FLARE)',
	[`VEHICLE_WEAPON_TANK`] = 'Tank Cannon (VEHICLE_WEAPON_TANK)',
	[`VEHICLE_WEAPON_SPACE_ROCKET`] = 'Rockets (VEHICLE_WEAPON_SPACE_ROCKET)',
	[`VEHICLE_WEAPON_PLAYER_LASER`] = 'Laser (VEHICLE_WEAPON_PLAYER_LASER)',
	[`AMMO_RPG`] = 'Rocket (AMMO_RPG)',
	[`AMMO_TANK`] = 'Tank (AMMO_TANK)',
	[`AMMO_SPACE_ROCKET`] = 'Rocket (AMMO_SPACE_ROCKET)',
	[`AMMO_PLAYER_LASER`] = 'Laser (AMMO_PLAYER_LASER)',
	[`AMMO_ENEMY_LASER`] = 'Laser (AMMO_ENEMY_LASER)',
	[`WEAPON_RAMMED_BY_CAR`] = 'Rammed by Car (WEAPON_RAMMED_BY_CAR)',
	[`WEAPON_BOTTLE`] = 'Bottle (WEAPON_BOTTLE)',
	[`WEAPON_GUSENBERG`] = 'Gusenberg Sweeper (WEAPON_GUSENBERG)',
	[`WEAPON_SNSPISTOL`] = 'SNS Pistol (WEAPON_SNSPISTOL)',
	[`WEAPON_VINTAGEPISTOL`] = 'Vintage Pistol (WEAPON_VINTAGEPISTOL)',
	[`WEAPON_DAGGER`] = 'Antique Cavalry Dagger (WEAPON_DAGGER)',
	[`WEAPON_FLAREGUN`] = 'Flare Gun (WEAPON_FLAREGUN)',
	[`WEAPON_HEAVYPISTOL`] = 'Heavy Pistol (WEAPON_HEAVYPISTOL)',
	[`WEAPON_SPECIALCARBINE`] = 'Special Carbine (WEAPON_SPECIALCARBINE)',
	[`WEAPON_MUSKET`] = 'Musket (WEAPON_MUSKET)',
	[`WEAPON_FIREWORK`] = 'Firework Launcher (WEAPON_FIREWORK)',
	[`WEAPON_MARKSMANRIFLE`] = 'Marksman Rifle (WEAPON_MARKSMANRIFLE)',
	[`WEAPON_HEAVYSHOTGUN`] = 'Heavy Shotgun (WEAPON_HEAVYSHOTGUN)',
	[`WEAPON_PROXMINE`] = 'Proximity Mine (WEAPON_PROXMINE)',
	[`WEAPON_HOMINGLAUNCHER`] = 'Homing Launcher (WEAPON_HOMINGLAUNCHER)',
	[`WEAPON_HATCHET`] = 'Hatchet (WEAPON_HATCHET)',
	[`WEAPON_COMBATPDW`] = 'Combat PDW (WEAPON_COMBATPDW)',
	[`WEAPON_KNUCKLE`] = 'Knuckle Duster (WEPAON_KNUCKLE)',
	[`WEAPON_MARKSMANPISTOL`] = 'Marksman Pistol (WEAPON_MARKSMANPISTOL)',
	[`WEAPON_MACHETE`] = 'Machete (WEAPON_MACHETE)',
	[`WEAPON_MACHINEPISTOL`] = 'Machine Pistol (WEAPON_MACHINEPISTOL)',
	[`WEAPON_FLASHLIGHT`] = 'Flashlight (WEAPON_FLASHLIGHT)',
	[`WEAPON_DBSHOTGUN`] = 'Double Barrel Shotgun (WEAPON_DBSHOTGUN)',
	[`WEAPON_COMPACTRIFLE`] = 'Compact Rifle (WEAPON_COMPACTRIFLE)',
	[`WEAPON_SWITCHBLADE`] = 'Switchblade (WEAPON_SWITCHBLADE)',
	[`WEAPON_REVOLVER`] = 'Heavy Revolver (WEAPON_REVOLVER)',
	[`WEAPON_FIRE`] = 'Fire (WEAPON_FIRE)',
	[`WEAPON_HELI_CRASH`] = 'Heli Crash (WEAPON_HELI_CRASH)',
	[`WEAPON_RUN_OVER_BY_CAR`] = 'Run over by Car (WEAPON_RUN_OVER_BY_CAR)',
	[`WEAPON_HIT_BY_WATER_CANNON`] = 'Hit by Water Cannon (WEAPON_HIT_BY_WATER_CANNON)',
	[`WEAPON_EXHAUSTION`] = 'Exhaustion (WEAPON_EXHAUSTION)',
	[`WEAPON_EXPLOSION`] = 'Explosion (WEAPON_EXPLOSION)',
	[`WEAPON_ELECTRIC_FENCE`] = 'Electric Fence (WEAPON_ELECTRIC_FENCE)',
	[`WEAPON_BLEEDING`] = 'Bleeding (WEAPON_BLEEDING)',
	[`WEAPON_DROWNING_IN_VEHICLE`] = 'Drowning in Vehicle (WEAPON_DROWNING_IN_VEHICLE)',
	[`WEAPON_DROWNING`] = 'Drowning (WEAPON_DROWNING)',
	[`WEAPON_BARBED_WIRE`] = 'Barbed Wire (WEAPON_BARBED_WIRE)',
	[`WEAPON_VEHICLE_ROCKET`] = 'Vehicle Rocket (WEAPON_VEHICLE_ROCKET)',
	[`WEAPON_BULLPUPRIFLE`] = 'Bullpup Rifle (WEAPON_BULLPUPRIFLE)',
	[`WEAPON_ASSAULTSNIPER`] = 'Assault Sniper (WEAPON_ASSAULTRIFLE)',
	[`VEHICLE_WEAPON_ROTORS`] = 'Rotors (VEHICLE_WEAPON_ROTORS)',
	[`WEAPON_RAILGUN`] = 'Railgun (WEAPON_RAILGUN)',
	[`WEAPON_AIR_DEFENCE_GUN`] = 'Air Defence Gun (WEAPON_AIR_DEFENCE_GUN)',
	[`WEAPON_AUTOSHOTGUN`] = 'Automatic Shotgun (WEAPON_AUTOSHOTGUN)',
	[`WEAPON_BATTLEAXE`] = 'Battle Axe (WEAPON_BATTLEAXE)',
	[`WEAPON_COMPACTLAUNCHER`] = 'Compact Grenade Launcher (WEAPON_COMPACTLAUNCHER)',
	[`WEAPON_MINISMG`] = 'Mini SMG (WEAPON_MINISMG)',
	[`WEAPON_PIPEBOMB`] = 'Pipebomb (WEAPON_PIPEBOMB)',
	[`WEAPON_POOLCUE`] = 'Poolcue (WEAPON_POOLCUE)',
	[`WEAPON_WRENCH`] = 'Wrench (WEAPON_WRENCH)',
	[`WEAPON_SNOWBALL`] = 'Snowball (WEAPON_SNOWBALL)',
	[`WEAPON_ANIMAL`] = 'Animal (WEAPON_ANIMAL)',
	[`WEAPON_COUGAR`] = 'Cougar (WEAPON_COUGAR)'
}

local weapon = {
	[`WEAPON_PISTOL`] = true,
	[`WEAPON_PISTOL_MK2`] = true,
	[`WEAPON_COMBATPISTOL`] = true,
	[`WEAPON_APPISTOL`] = true,
	[`WEAPON_STUNGUN`] = true,
	[`WEAPON_CARBINERIFLE`] = true,
	[`WEAPON_CARBINERIFLE_MK2`] = true, 
	[`WEAPON_SMG`] = true,
	[`WEAPON_ASSAULTRIFLE`] = true,
	[`WEAPON_MINISMG`] = true,
	[`WEAPON_COMPACTRIFLE`] = true,
}

function GetPedBoneLabelOrName(bone)
	if Bones[bone] then
		return Bones[bone].label or Bones[bone].name
	end

	return bone
end

RegisterCommand("combatlog", function()
	local playerPed = PlayerPedId()
    local bone = GetPedLastDamageBone(GetPlayerPed(-1))
    local bonelabel = GetPedBoneLabelOrName(bone)
	local victim = GetPlayerName(PlayerId())
	local victimId = GetPlayerServerId(PlayerId())
	local attacker = GetPlayerServerId(GetPedSourceOfDeath(PlayerPedId()))
	--local attacker = GetPlayerName(attackerId)
    local health = GetEntityHealth(playerPed)
	local newHealth = GetEntityHealth(playerPed)
	local dead = IsEntityDead(playerPed)
    if bone == false then
        print("bone is nill")
    else
        print("bone is: "..bonelabel.."")
    end
	--[[ocal data = {
		victim = victim,
		attacker = victim,
        bone = GetPedBoneLabelOrName(bone),
		--attackerId = victimId,
		--weapon = data.weapon or "Unknown",
        weapon = tostring(Weapons[weapon] or weapon),
		weaponHash = 0,
		health = health,
		newHealth = newHealth,
		distance = 0.0,
		speedAttacker = 0.0,
		speedVictim = GetEntitySpeed(playerPed),
        damage = GetWeaponDamageModifier(GetPedCauseOfDeath(PlayerPedId())),
		weaponDamage = 0.0,
		playerMeleeDamage = 0.0,
		playerWeaponDamage = 0.0
	}
	health = newHealth
    local msg = ("attacker: %s victim: %s where: %s damage: %s oldHealth: %s newHealth: %s distance: %s weapon: %s"):format(attacker, victim, data.bone, data.damage, health, data.newHealth, data.distance, data.weapon)
	--print(msg)]]
end)